### ISSUE TITLE
Overbodig

### ISSUE THREAD

**Issue by RichardRam87** [Chequered/Mythe#2]
``` c
 public void PickUp(Transform newParent)
    {
        transform.parent = newParent;
        hasBeenHooked = true;
    }

    public int GetPointWorth()
    {
        return points;
    } 
```

Bestand: https://github.com/Chequered/Mythe/blob/master/Assets/Scripts/Entities/Fish/FishPickup.cs

Deze functies heb je ook al verwerkt in je base class en zijn dubbelop.

**Comment by DaanRuiter** [comment]
Inderdaad, bedankt voor de heads up!
