### ISSUE TITLE
Statics

### ISSUE THREAD

**Issue by RichardRam87** [Chequered/Mythe#4]
``` c
  public static Quaternion Lookat2D(Transform origin, Transform target)
    {
        //works like transform.LookAt() but than in a 2D fashion.
        Quaternion rotation = Quaternion.LookRotation(target.transform.position - origin.position, origin.TransformDirection(Vector3.up));
        return new Quaternion(0, 0, rotation.z, rotation.w);
    } 
```

Bestand: https://github.com/Chequered/Mythe/blob/master/Assets/Scripts/Player/HarpoonAimer.cs

Waarom is deze functie static? Is dit echt nodig, of uit gemak van bereikbaarheid?

**Comment by DaanRuiter** [comment]
Ik had hem static gemaakt zodat we het nog in vaker kunnen gebruiken als we meer objecten naar bepaalde posities wil laten kijken.

**Comment by RichardRam87** [comment]
Is het in dat geval dat niet een soort van Utility functie van je engine waar deze (en ook andere classes) gebruik van kunnen maken? Net zoals bijvoorbeeld de Vector3.Normalize() functie?
