### ISSUE TITLE
Enum consistentie

### ISSUE THREAD

**Issue by RichardRam87** [Chequered/Mythe#5]
``` c
public enum MovementDirection
{
    None,
    Down,
    Up
} 
```

Bestand: https://github.com/Chequered/Mythe/blob/master/Assets/Scripts/Player/HarpoonController.cs

Wees consistent in je code conventions voor enums. In je interactable class beginnen je enums met een kleine letter. 
Met of zonder hoofdletter zijn geen harde regels voor, ik gebruik altijd een hoofdletter.

**Comment by DaanRuiter** [comment]
Dat komt waarschijnlijk omdat ik deze heb bemaakt, en de gene in interactable heeft Niek gemaakt, ik zal het oplossen.
