### ISSUE TITLE
Dubbelop?

### ISSUE THREAD

**Issue by RichardRam87** [Chequered/Mythe#9]
``` c
 public void AddScore(int pointsToAdd)
    {
        points += pointsToAdd;
        pointText.text = "Points: " + points;
    }

    public void AddGold(int goldToAdd)
    {
        gold += goldToAdd;
        goldText.text = "Gold: " + gold;
    }

    public void SetStats(int gold , int points)
    {
        this.points = points;
        this.gold = gold;
        pointText.text = "Points: " + points;
        goldText.text = "Gold: " + gold;

```

Bestand: https://github.com/Chequered/Mythe/blob/master/Assets/Scripts/World/Game.cs

Heb je dit soort functies niet verwerkt in het Gold en Score class? Zoja, dan is dit een beetje dubbelop.

**Comment by DaanRuiter** [comment]
ja ik had deze gemaakt om het score systeem te testen. Terwijl Koen een beter systeem maakte die ik nog niet kon gebruiken.

**Comment by RichardRam87** [comment]
Okido, helemaal goed. Refactor je code wanneer je deze functies niet meer nodig hebt.
